version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      actions-non-major:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      gomod-non-major:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      npm-non-major:
        applies-to: version-updates
        update-types:
          - minor
          - patch
